import { AlertOutlined, CheckCircleOutlined, ClockCircleOutlined, MessageOutlined, ReloadOutlined, SearchOutlined, SettingOutlined } from "@ant-design/icons";
import type { AppPage, PageState } from "../model";
import { paginate, Pagination } from "../components/Pagination";

type Props = { page: Extract<AppPage, "alerts" | "logs" | "audit">; query: string; level: string; module: string; paging: PageState; onQuery: (value: string) => void; onLevel: (value: string) => void; onModule: (value: string) => void; onPaging: (state: PageState) => void; onNotice: (message: string) => void };

export function OperationsPage({ page, query, level, module, paging, onQuery, onLevel, onModule, onPaging, onNotice }: Props) {
  const title = page === "alerts" ? "告警通知" : page === "logs" ? "日志中心" : "操作审计";
  const rows = page === "alerts" ? [["严重", "县中医院检查申请单链路失败", "数据同步", "连接源端 oracle-zyy 超时", "12:12", "未处理"], ["警告", "收费明细记录校验发现差异", "数据校验", "发现 136 行差异", "11:43", "处理中"], ["警告", "病案首页手术待配置", "配置管理", "采集链路缺少源端映射", "10:05", "未处理"], ["提示", "基层医疗共享全量同步完成", "数据同步", "9 家机构写入 48.6 万行", "09:48", "已关闭"]] : page === "logs" ? [["INFO", "task-runner", "TASK-1419 启动增量同步", "admin", "12:18:02", "req_a91f"], ["ERROR", "datasource", "oracle-zyy 连接超时", "system", "12:12:08", "req_7c31"], ["INFO", "validation", "VAL-1399 校验完成，差异 136 行", "system", "11:43:19", "req_4e17"], ["WARN", "scheduler", "任务 TASK-1418 达到重试上限", "system", "08:01:54", "req_b26d"]] : [["更新", "编辑县中医院采集链路", "admin", "配置管理", "192.168.1.18", "12:09:31"], ["执行", "手动运行 TASK-1419", "admin", "数据同步", "192.168.1.18", "12:08:02"], ["启用", "启用消息通知 ODS_YL_APP_JIANYANSQD", "admin", "数据集管理", "192.168.1.18", "11:52:44"], ["登录", "系统登录成功", "admin", "认证", "192.168.1.18", "08:30:17"]];
  const normalized = query.trim().toLowerCase();
  const filtered = rows.filter((row) => (!normalized || row.join("").toLowerCase().includes(normalized)) && (level === "全部级别" || row[0] === level) && (module === "全部模块" || row.some((cell) => cell === module)));
  const current = paginate(filtered, paging);
  const resetPage = (next: () => void) => { next(); onPaging({ ...paging, page: 1 }); };
  return <>
    {page === "alerts" && <section className="stat-grid compact-stats"><article><div className="stat-icon red"><AlertOutlined /></div><div><span>未处理</span><strong>2</strong></div></article><article><div className="stat-icon amber"><ClockCircleOutlined /></div><div><span>处理中</span><strong>1</strong></div></article><article><div className="stat-icon green"><CheckCircleOutlined /></div><div><span>已关闭</span><strong>1</strong></div></article><article><div className="stat-icon blue"><MessageOutlined /></div><div><span>通知渠道</span><strong>2</strong></div></article></section>}
    <section className="data-card management-card"><div className="toolbar management-toolbar"><select value={level} onChange={(event) => resetPage(() => onLevel(event.target.value))}><option>全部级别</option>{page === "alerts" ? <><option>严重</option><option>警告</option><option>提示</option></> : <><option>INFO</option><option>WARN</option><option>ERROR</option></>}</select><select value={module} onChange={(event) => resetPage(() => onModule(event.target.value))}><option>全部模块</option><option>数据同步</option><option>数据校验</option><option>配置管理</option></select><label className="search-box wide-search"><SearchOutlined /><input value={query} onChange={(event) => resetPage(() => onQuery(event.target.value))} placeholder={`搜索${title}`} /></label><div className="toolbar-spacer" /><button className="secondary-button" onClick={() => onNotice(`${title}已刷新`)}><ReloadOutlined /> 刷新</button>{page === "alerts" && <button className="primary-button" onClick={() => onNotice("告警规则入口已打开")}><SettingOutlined /> 告警规则</button>}{page === "logs" && <button className="secondary-button" onClick={() => onNotice("已生成日志导出任务")}>导出日志</button>}</div><div className="table-scroll"><table className="resource-table operation-table"><thead><tr>{(page === "alerts" ? ["级别", "告警内容", "来源", "详情", "发生时间", "状态"] : page === "logs" ? ["级别", "服务", "消息", "用户", "时间", "请求 ID"] : ["操作", "操作内容", "操作人", "模块", "IP 地址", "时间"]).map((head) => <th key={head}>{head}</th>)}<th className="action-col">操作</th></tr></thead><tbody>{current.rows.map((row, rowIndex) => <tr key={rowIndex}>{row.map((cell, index) => <td key={index}>{index === 0 ? <b className={`operation-level level-${cell}`}>{cell}</b> : cell}</td>)}<td className="action-col"><button className="text-button" onClick={() => onNotice(page === "alerts" ? "告警已进入处理流程" : "详情已打开")}>{page === "alerts" ? "处理" : "详情"}</button></td></tr>)}</tbody></table></div><Pagination total={filtered.length} state={paging} onChange={onPaging} /></section>
  </>;
}
